version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.debug
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
