FROM node:16-alpine

WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json", "./"]
RUN npm install

RUN apk add vim

RUN chown node:node /usr/src/app/node_modules

COPY --chown=node:node ./ ./

USER node

EXPOSE 3000

CMD npm start